# Generated by Django 4.2.19 on 2025-03-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="listing", name="img",),
        migrations.AddField(
            model_name="listing",
            name="propic",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
