# Generated by Django 4.2.19 on 2025-03-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_remove_listing_img_listing_propic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing", old_name="propic", new_name="img",
        ),
    ]
