# Generated by Django 4.2.19 on 2025-02-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "members",
            "0003_user_propic_alter_user_email_alter_user_user_id_ride_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("token", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("user_id", models.IntegerField()),
                ("is_used", models.BooleanField(default=False)),
            ],
        ),
    ]
