# Generated by Django 5.1.6 on 2025-02-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_user_propic_alter_user_email_alter_user_user_id_ride_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('user_id', models.IntegerField()),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='tag',
            field=models.CharField(choices=[('notag', 'No Tag'), ('clothing', 'Clothing'), ('misc', 'Miscellaneous'), ('electronics', 'Electronics'), ('schoolsupp', 'School Supplies'), ('free', 'Free'), ('transport', 'Transport'), ('service', 'Service'), ('tutoring', 'Tutoring'), ('careercoach', 'Career Coaching'), ('moving', 'Moving Help'), ('researchassist', 'Research Assistance')], default='notag', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
