# Generated by Django 4.2.19 on 2025-03-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_rename_propic_listing_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="listing_image/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="propic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pic/"),
        ),
    ]
