# Generated by Django 5.1.6 on 2025-02-26 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_token_alter_listing_tag_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user_id_1',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user_id_2',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='user_id_1',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='user_id_2',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user_id_1',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user_id_2',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Ride',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
