# Generated by Django 4.2.19 on 2025-04-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_alter_listing_img_alter_user_propic"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="auth", field=models.BooleanField(default=False),
        ),
    ]
