# Generated by Django 4.2.19 on 2025-02-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_alter_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="tag",
            field=models.CharField(
                choices=[
                    ("notag", "No Tag"),
                    ("clothing", "Clothing"),
                    ("misc", "Miscellaneous"),
                    ("electronics", "Electronics"),
                    ("schoolsupp", "School Supplies"),
                    ("free", "Free"),
                    ("transport", "Transport"),
                    ("service", "Service"),
                    ("tutoring", "Tutoring"),
                    ("careercoach", "Career Coaching"),
                    ("moving", "Moving Help"),
                    ("researchassist", "Research Assistance"),
                ],
                default="notag",
                max_length=20,
            ),
        ),
    ]
