# Generated by Django 4.2.19 on 2025-02-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_alter_listing_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_num",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="real_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
