# Generated by Django 4.2.19 on 2025-02-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_alter_user_phone_num_alter_user_profile_name_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="user", old_name="user_id", new_name="id",),
    ]
