# Generated by Django 4.2.19 on 2025-02-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_rename_user_id_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction", old_name="user_id_1", new_name="id_1",
        ),
        migrations.RenameField(
            model_name="transaction", old_name="user_id_2", new_name="id_2",
        ),
    ]
