# Generated by Django 4.2.19 on 2025-02-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_rename_user_id_1_transaction_id_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
