# Generated by Django 4.2.19 on 2025-02-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0010_user_is_active_user_is_staff_user_last_login"),
    ]

    operations = [
        migrations.RenameField(model_name="listing", old_name="user", new_name="id",),
    ]
