# Generated by Django 4.2.19 on 2025-02-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0012_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(name="user", managers=[],),
    ]
